### ISSUE TITLE
dblclick event listener overriden by double-click-to-zoom on mobile

### ISSUE THREAD

**Issue by evnchn** [hwtam/mai-search#1]
Background: Double click is used for search on Youtube for mai-tools page to maintain single-click for original functionality

Problem: Cannot double click to search on YouTube for mai-tools pagebecause double-click-to-zoom consumes the double-click event. 

Solution: Add the CSS in https://stackoverflow.com/a/53236027

_Tested on my device_

**Comment by hwtam** [comment]
done in [this commit](https://github.com/hwtam/mai-search/commit/5bb743917b9b59605dafcdd4b05943ff4429010d). :)
